### ISSUE TITLE
Attempt on connectivity-search-manuscript produced aggressive suggestions

### ISSUE THREAD

**Issue by dhimmel** [manubot/manubot-ai-editor#13]
I just attempted to dispatch the [ai-revision](https://github.com/greenelab/connectivity-search-manuscript/blob/d0b460d253f8577104656c11b0ef492b7deadbdc/.github/workflows/ai-revision.yaml) workflow for connectivity-search-manuscript in [this job](https://github.com/greenelab/connectivity-search-manuscript/actions/runs/4622682569/jobs/8175652648).

The revise step logged:

```
Using language model from environment variable 'AI_EDITOR_LANGUAGE_MODEL'
Language model:  text-davinci-003
File names to revise: {'05.main-text.md'}
```

But took zero seconds and no output branch or PR was created. @miltondp any idea what happened?

**Comment by dhimmel** [comment]
Hmm possibly it only works with preset file names?

https://github.com/manubot/manubot-ai-editor/blob/a571f4dde356a212d3e37fc0d6c5a8ff67e5b935/libs/manubot_ai_editor/editor.py#L190-L205

**Comment by dhimmel** [comment]
Got it working with these tweaks in 6606ed37efc717782ad67531a7c6760c35ceccc8 with a PR at https://github.com/greenelab/connectivity-search-manuscript/pull/48. It went a bit wild with rewriting, so probably won't end up using.

Basically what I'm looking for is:

- copyediting at the entire manuscript scope for typos, grammar issues, misspellings, etcetera.
- shortening of select sections, possibly with custom promps

For the second point, perhaps there's a construct where certain HTML comments in the source markdown can activate chatgpt for specific ranges, with each comment being able to specify a preset or even custom prompt.

**Comment by cgreene** [comment]
I'm surprised by how aggressive it was with the rewrite. I agree that, in this case, it's going to create more work.

**Comment by miltondp** [comment]
Hi @dhimmel. Sorry for the late reply. I was out of town. Thank you for your feedback! I'm sorry it didn't work as expected for you. Some suggested changes don't make any sense.

The current prompts are very "hands-on", with specific instructions for different sections, and that's probably influencing this output. Lately, I was trying to use a prompt like "proofread and revise the following paragraph" in ChatGPT and it seems to work well. It might be what you are looking for. However, we don't have yet support for custom prompts in the `manubot-ai-editor`. I will try to add some basic support and see if it helps. I will let you know.

I also agree that a more verbose output should indicate if no files were found. I created issue #14 for that.

**Comment by miltondp** [comment]
I'm changing the title of the issue to reflect the problem of aggressive editing.

@dhimmel, I change `manubot-ai-editor` to [support basic custom prompts](https://pypi.org/project/manubot-ai-editor/0.4.2/). The latest version should be automatically installed everywhere now. I also created a [PR in your manuscript repo](https://github.com/dhimmel/connectivity-search-manuscript/pull/1) if you want to give it a try. The custom prompt "proofreads and revises" each paragraph, without any section-specific instructions. You can also try to include "proofread" only in the prompt, but the actual one seems to work.

**Comment by dhimmel** [comment]
I tried and proofread and revise in https://github.com/greenelab/connectivity-search-manuscript/pull/51, but the results are too aggressive. I think I should retry with just proofread.

**Comment by dhimmel** [comment]
The proofread only prompt was less aggressive as noted in https://github.com/greenelab/connectivity-search-manuscript/pull/51#issuecomment-1559206047. It used:

```yaml
AI_EDITOR_CUSTOM_PROMPT: "Proofread the following paragraph"
```

Ended up taking several suggestions from it in https://github.com/greenelab/connectivity-search-manuscript/commit/8ad541fbe6791be7cb74c90c62ae8334cb1800e6.

**Comment by miltondp** [comment]
Thank you for the feedback, @dhimmel!
